version: 2
run:
  timeout: 5m
  go: "1.21"
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - forcetypeassert
    - funlen
    - contextcheck
    - gocognit
    - goconst
    - nolintlint
    # - cyclop
    # - err113
    - whitespace
    - wsl
    - unused
    # - wrapcheck
    # - gocritic
    # - gofumpt is a formatter (moved to formatters below)
    - lll        # line length linter
formatters:
  enable:
    - gofmt
    - goimports
formatters-settings:
  gofmt:
    simplify: true
linters-settings:
  # cyclop:
  #   max-complexity: 30
  #   min-complexity: 30
  revive:
    ignore-generated-header: true
  lll:
    line-length: 100
    tab-width: 1
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
